print ('Hello World')
print ("Hello World")
print ("Jhon Kennedy")
print( 25)
print (2*2)
print (2+5+9)
print ("Hello,","I'am","Jhon")
print ("Jhon","is",20,"years","old")
print ("Hello Jhon,"+"How are you?")
print ("I am 20 years  old"+"and"+"My friend is 21 years old.")
print("20" +"+" +"2"+"+"+"22")

